'use client';
import {useEffect,useState} from 'react';
export default function Dashboard(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[sort,setSort]=useState('conversions');
 useEffect(()=>{let active=true;setError('');setData(null);fetch('/api/stats?'+new URLSearchParams({from,to}),{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'조회 실패');if(active)setData(d);}).catch(()=>{if(active)setError('집계 조회에 실패했습니다. 관리자 인증·서버 설정·기간을 확인해 주세요.');});return()=>{active=false;};},[from,to]);
 function preset(days){const now=new Date();setTo(days?now.toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}):'');setFrom(days?new Date(+now-(days-1)*86400000).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}):'');}
 const rate=x=>x.clicks?x.conversions/x.clicks*100:0;
 const daily=data?.daily||[],max=Math.max(1,...daily.flatMap(d=>[Number(d.clicks),Number(d.conversions)]));
 function points(key){return daily.map((d,i)=>(40+(daily.length===1?0:i/(daily.length-1))*900)+','+(200-Number(d[key])/max*170)).join(' ');}
 return <><div className="tool-heading"><div><p className="eyebrow">AVENIQ / CAMPAIGN PERFORMANCE</p><h1>성과 대시보드</h1></div><span>한국시간 · 클릭 대비 전환</span></div>
 <p className="tool-note">전환은 UTM과 랜딩 경로가 일치하는 신청 저장 성공 건수입니다. 고유 인원 수가 아니며, 반복 신청·긴 링크 직접 방문으로 전환율이 100%를 넘을 수 있습니다. 방문 대비 전환은 GA4에서 확인하세요. 현재 실제 신청 접수는 준비 중입니다.</p>
 <div className="actions">{[['오늘',1],['7일',7],['30일',30],['전체',0]].map(([label,n])=><button key={label} onClick={()=>preset(n)}>{label}</button>)}</div>
 <div className="tool-fields"><label>시작일<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>종료일 (포함)<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
 {error?<p role="alert">{error}</p>:!data?<p role="status">집계 불러오는 중…</p>:<>
 <div className="metric-grid">{[['클릭',data.summary.clicks],['전환(건)',data.summary.conversions],['전환율',data.summary.clicks?rate(data.summary).toFixed(1)+'%':'—'],['현재 활성 링크',data.summary.active]].map(([label,value])=><div className="metric" key={label}>{label}<strong>{value}</strong></div>)}</div>
 <section className="tool-panel"><h2>채널별 성과</h2><label>정렬<select value={sort} onChange={e=>setSort(e.target.value)}><option value="conversions">전환 높은 순</option><option value="clicks">클릭 높은 순</option><option value="rate">전환율 높은 순</option></select></label><table><thead><tr><th>채널</th><th>클릭</th><th>전환</th><th>전환율</th></tr></thead><tbody>{[...data.channels].sort((a,b)=>sort==='rate'?rate(b)-rate(a):b[sort]-a[sort]).map(c=><tr key={c.id||'manual'}><td>{c.name}</td><td>{c.clicks}</td><td>{c.conversions}</td><td>{c.clicks?rate(c).toFixed(1)+'%':'—'}</td></tr>)}</tbody></table></section>
 <section className="tool-panel"><h2>일별 추이</h2><p>남색: 클릭 · 금색: 전환 · 동일한 건수 축</p>{daily.length?<><svg className="daily-chart" viewBox="0 0 980 230" role="img" aria-label="클릭과 전환 일별 추이. 자세한 값은 아래 표에 표시됩니다."><line x1="40" y1="200" x2="940" y2="200" stroke="#bbb"/><text x="0" y="35">{max}</text><text x="10" y="200">0</text><polyline fill="none" stroke="#183b4b" strokeWidth="3" points={points('clicks')}/><polyline fill="none" stroke="#a97e30" strokeWidth="3" points={points('conversions')}/>{daily.map((d,i)=><g key={d.day}><circle cx={40+(daily.length===1?0:i/(daily.length-1))*900} cy={200-Number(d.clicks)/max*170} r="3" fill="#183b4b"/><circle cx={40+(daily.length===1?0:i/(daily.length-1))*900} cy={200-Number(d.conversions)/max*170} r="3" fill="#a97e30"/></g>)}<text x="40" y="225">{daily[0].day}</text><text x="830" y="225">{daily.at(-1).day}</text></svg><details><summary>일별 수치 표</summary><table><thead><tr><th>날짜</th><th>클릭</th><th>전환</th></tr></thead><tbody>{daily.map(d=><tr key={d.day}><td>{d.day}</td><td>{d.clicks}</td><td>{d.conversions}</td></tr>)}</tbody></table></details></>:<p>선택 기간에 기록된 데이터가 없습니다.</p>}</section>
 <section className="tool-panel"><h2>소재 상위 목록</h2><p>전환율 순 · 표본이 적은 링크는 클릭 수와 함께 판단하세요.</p><table><thead><tr><th>소재 / 메모</th><th>클릭</th><th>전환</th><th>전환율</th></tr></thead><tbody>{data.materials.filter(l=>l.clicks>0).sort((a,b)=>rate(b)-rate(a)||b.clicks-a.clicks).slice(0,20).map(l=><tr key={l.id}><td>{l.content||'소재 없음'} · {l.label}{l.archived?' (보관)':''}</td><td>{l.clicks}</td><td>{l.conversions}</td><td>{rate(l).toFixed(1)}%</td></tr>)}</tbody></table></section>
 </>}</>;
}
