import Image from 'next/image';
import SignupForm from './signup-form';
import { getConfig } from '../lib/config.mjs';
export const dynamic = 'force-dynamic';

export default function Home() {
  const config = getConfig();
  return <main>
    <section className="hero" aria-labelledby="hero-title"><div className="hero-copy">
      <p className="eyebrow"><span className="dot"/> AFTER CHUSEOK · 가상 오픈</p>
      <h1 id="hero-title">연휴가 끝나면,<br/><em>나를 챙기는 한 잔부터.</em></h1>
      <p className="intro">산뜻한 과일티로 시작하는 가을 루틴.<br/>단백질 드링크까지, 일상 가까이 만나는 AVENIQ.</p>
      <a className="button" href="#signup">출시 알림 신청하기 <span aria-hidden="true">↗</span></a>
      <p className="hero-note">추석 이후 오픈을 가정한 이벤트 미리보기 · 실제 접수·판매 없음</p>
    </div><div className="hero-visual"><Image src="/tea.webp" alt="AVENIQ 3PM STICK TEA 패키지와 유자빛 티 한 잔의 제품 콘셉트" fill sizes="(max-width: 760px) 100vw, 55vw" priority/><p className="image-note">티 제품 콘셉트 · 구성·원료·표시사항은 출시 시 확정</p></div></section>
    <section className="brand-story" aria-labelledby="brand-title"><p className="eyebrow">EVERYDAY, YOUR WAY</p><h2 id="brand-title">거창한 관리보다,<br/>내가 좋아하는 한 잔부터.</h2><p>일상 가까이에서 만나는 합리적인 웰니스 음료를 준비합니다.<br/>편의점과 생활용품점에서도 부담 없이 고를 수 있도록.</p><div className="range"><article><span>01 / PROTEIN DRINK</span><h3>단백질 드링크</h3><p>바쁜 일상에 간편하게 더하는 한 잔.<br/>취향에 맞는 단백질 음료를 준비 중입니다.</p></article><article><span>02 / FRUIT TEA</span><h3>과일티</h3><p>잠깐의 여유에 산뜻한 맛을 더하는 한 잔.<br/>과일의 풍미를 담은 티를 준비 중입니다.</p></article></div><p className="fine">제품군 기획 단계이며 출시 품목·성분·영양정보는 확정 후 안내합니다. 특정 유통 채널 입점은 확정되지 않았습니다.</p></section><section className="benefit" aria-labelledby="benefit-title"><div><p className="eyebrow">FIRST SIP, FIRST BENEFIT</p><h2 id="benefit-title">첫 만남은<br/>조금 더 가볍게.</h2></div><div className="price-panel"><span className="pill">첫 구매 1,000원 할인 예정</span><div className="price"><del>3,900원</del><span aria-hidden="true">→</span><strong>2,900<span>원</span></strong></div><p>알림 신청자에게 준비하는 첫 구매 혜택.<br/>출시 일정과 쿠폰 이용 방법을 함께 안내할 예정입니다.</p><p className="fine">기획 기준가 3,900원 · 적용 상품·구성은 확정 후 안내<br/>고객당 1회 · 쿠폰 발급 후 7일 이내 사용 예정<br/>출시일과 판매처는 확정 후 안내합니다. 현재 결제는 진행되지 않습니다.</p></div></section>
    <section className="signup-section" id="signup" aria-labelledby="signup-title"><div className="signup-copy"><p className="eyebrow">BE THE FIRST</p><h2 id="signup-title">새로운 루틴의<br/>시작을 함께해요.</h2><p>출시 알림 신청하고,<br/>첫 구매 1,000원 할인 소식 만나기.</p><ol className="steps"><li><span>01</span> 알림 신청</li><li><span>02</span> 출시 소식 확인</li><li><span>03</span> 첫 구매 혜택 사용</li></ol><p className="fine">광고성 할인·이벤트 메시지는 선택한 수신 채널에 동의한 경우에만 발송합니다.</p></div><SignupForm enabled={config.enabled} days={config.days}/></section>
<section className="faq-section" id="faq" aria-labelledby="faq-title"><div className="faq-intro"><p className="eyebrow">FAQ</p><h2 id="faq-title">한 잔의 여유,<br/>궁금한 점은 여기서.</h2><Image src="/otter-tea.webp" alt="남색 후드와 베이지 가방을 착용하고 차를 마시는 수달 캐릭터" width={1024} height={1024} sizes="(max-width: 760px) 85vw, 32vw"/><p className="fine">브랜드 캐릭터 연출 이미지</p></div><div className="faq-list"><details><summary>언제 오픈하나요?</summary><p>추석 이후 가을 시즌에 오픈하는 상황을 가정한 가상 이벤트입니다. 실제 출시일과 이벤트 기간은 아직 확정되지 않았습니다.</p></details><details><summary>어떤 제품을 준비하고 있나요?</summary><p>과일티와 단백질 드링크를 기획하고 있습니다. 사진은 티 제품 콘셉트이며, 실제 출시 품목·원료·영양정보·구성은 확정 후 안내합니다.</p></details><details><summary>가격과 첫 구매 할인은 어떻게 되나요?</summary><p>기획 기준가는 3,900원이며 첫 구매 1,000원 할인 후 2,900원을 예정하고 있습니다. 고객당 1회, 쿠폰 발급 후 7일 이내 사용을 계획하고 있으며 실제 적용 조건은 출시 시 안내합니다.</p></details><details><summary>사진 속 티 세트가 2,900원인가요?</summary><p>아닙니다. 사진은 패키지 콘셉트입니다. 2,900원 혜택의 적용 상품과 수량은 미정이며 사진 속 세트 가격을 의미하지 않습니다.</p></details><details><summary>어디에서 살 수 있나요?</summary><p>편의점과 생활용품점 등 부담 없이 만날 수 있는 채널을 목표로 준비하고 있습니다. CU·다이소 등 특정 업체 입점이나 제휴는 확정되지 않았습니다.</p></details><details><summary>어떻게 마시나요?</summary><p>티의 물 양·온도·섭취 방법은 최종 제품 표시사항에 따라 안내할 예정입니다. 캐릭터가 차를 마시는 장면은 브랜드 연출이며 실제 사용법이나 효능을 보증하지 않습니다.</p></details><details><summary>이메일 없이도 신청할 수 있나요?</summary><p>접수 개시 후 휴대폰 번호는 필수, 이메일은 선택입니다. 이메일 광고성 정보 수신 동의를 선택한 경우에만 이메일 주소가 필요합니다. 문자·이메일 수신 동의는 각각 선택할 수 있습니다.</p></details><details><summary>지금 신청하거나 구매할 수 있나요?</summary><p>현재는 가상 이벤트 미리보기로 개인정보 접수와 결제는 진행하지 않습니다. 운영자 정보·보관 기간·관련 안내와 접수 절차를 확정한 뒤 신청을 열 예정입니다.</p></details></div></section>
  </main>;
}
