'use client';
import {useEffect,useState} from 'react';
import {CAMPAIGN,SITE_ORIGIN,normalize,makeUrl,suggestion} from '../../lib/utm.mjs';
export default function UtmTool(){
 const [data,setData]=useState({channels:[],links:[]}),[selected,setSelected]=useState([]),[form,setForm]=useState({campaign:CAMPAIGN,content:'',label:'',created_by:'',source:'',medium:'',term:'',short_code:''}),[manual,setManual]=useState(false),[edited,setEdited]=useState(false),[status,setStatus]=useState('불러오는 중…'),[busy,setBusy]=useState(false),[result,setResult]=useState([]),[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[archived,setArchived]=useState(false),[qr,setQr]=useState('');
 async function load(){const r=await fetch('/api/utm-links',{cache:'no-store'});if(!r.ok){setStatus('관리자 인증 또는 DB 설정이 필요합니다.');return;}setData(await r.json());setStatus('');}
 useEffect(()=>{load().catch(()=>setStatus('연결하지 못했습니다.'));try{setForm(f=>({...f,created_by:localStorage.getItem('aveniq.creator')||''}));}catch{}},[]);
 function choose(id){const next=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id];setSelected(next);if(!edited){const c=data.channels.find(c=>c.id===next[0]);setForm(f=>({...f,content:c?suggestion(c,data.links):''}));}}
 function field(key,value){setForm(f=>({...f,[key]:value}));if(key==='content')setEdited(true);}
 async function mutate(url,method,body){setBusy(true);setStatus('저장 중…');try{const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.error||'저장에 실패했습니다.');await load();return v;}catch(e){setStatus(e.message);return null;}finally{setBusy(false);}}
 async function copy(value){try{await navigator.clipboard.writeText(value);setStatus('복사했습니다.');}catch{setStatus('자동 복사가 차단되었습니다. 표시된 링크를 직접 복사해 주세요.');}}
 async function create(e){e.preventDefault();try{localStorage.setItem('aveniq.creator',form.created_by);}catch{}const v=await mutate('/api/utm-links','POST',{...form,manual,channelIds:selected});if(v){setResult(v.links);setStatus(v.links.some(l=>l.reused)?'기존 조합은 원래 링크를 반환했습니다.':'링크가 저장되었습니다.');if(v.links.length===1)await copy(SITE_ORIGIN+'/l/'+v.links[0].short_code);}}
 async function showQr(link){try{const {default:QRCode}=await import('qrcode');setQr(await QRCode.toDataURL(link,{width:320,margin:2}));}catch{setStatus('QR을 만들지 못했습니다.');}}
 const channels=data.channels.filter(c=>c.active),targets=manual?[{id:'manual',name:'수동 링크',source:form.source,medium:form.medium}]:selected.map(id=>channels.find(c=>c.id===id)).filter(Boolean);
 const links=data.links.filter(l=>(archived||!l.archived)&&(!filter||l.channel_id===filter)&&[l.label,l.short_code,l.content,l.campaign].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <><div className="tool-heading"><div><p className="eyebrow">AVENIQ / CAMPAIGN WORKSPACE</p><h1>UTM 링크 빌더</h1></div><span>홈페이지 · 한국시간</span></div>
 <p className="tool-note">등록한 채널별 링크를 만들고 공유하세요. 이름은 영문 소문자·숫자·점·밑줄·하이픈으로 정리됩니다. 실제 채널만 등록해 주세요.</p>
 <p role="status" aria-live="polite">{status}</p>
 <form onSubmit={create} className="tool-panel"><h2>1. 채널 선택</h2><label><input type="checkbox" checked={manual} onChange={e=>setManual(e.target.checked)}/> 수동 링크</label>
 {!manual&&<div className="channel-grid">{channels.length===0?<p>등록된 채널이 없습니다. 아래 ‘채널 관리’에서 첫 채널을 추가하세요.</p>:channels.map(c=><label key={c.id} className={'channel-card '+(selected.includes(c.id)?'selected':'')}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>choose(c.id)}/><strong>{c.name}</strong><span>{c.source} / {c.medium}</span><small>{c.note}</small><span>{data.links.filter(l=>l.channel_id===c.id).length}개 링크</span></label>)}</div>}
 <h2>2. 소재와 메모</h2><div className="tool-fields">
 <label>소재 코드<input value={form.content} onChange={e=>field('content',e.target.value)} onBlur={()=>field('content',normalize(form.content))} placeholder="소재 방식에 따라 자동 제안"/></label>
 <label>메모<input value={form.label} maxLength={160} onChange={e=>field('label',e.target.value)} placeholder="비우면 채널명 · 소재"/></label>
 <label>만든 사람<input value={form.created_by} maxLength={80} onChange={e=>field('created_by',e.target.value)} placeholder="이 브라우저에 기억"/></label></div>
 <details open={manual||undefined}><summary>고급 설정</summary><div className="tool-fields">{['source','medium','campaign','term','short_code'].map(k=><label key={k}>{k}<input value={form[k]} onChange={e=>field(k,e.target.value)} onBlur={()=>field(k,normalize(form[k]))} required={k==='campaign'||(manual&&['source','medium'].includes(k))}/></label>)}</div><p>고급 source/medium은 선택한 모든 채널에 적용됩니다. 직접 단축 코드는 한 링크만 만들 때 지정하세요.</p></details>
 <h2>3. 미리보기</h2>{targets.map(c=><div className="link-preview" key={c.id}><strong>{c.name}</strong><code>{form.short_code?SITE_ORIGIN+'/l/'+normalize(form.short_code):SITE_ORIGIN+'/l/'+(c.code||'link')+'-[저장 시 확정]'}</code><code>{makeUrl({...form,source:form.source||c.source,medium:form.medium||c.medium})}</code></div>)}
 <button disabled={busy||targets.length===0} type="submit">{targets.length>1?targets.length+'개 만들기':'링크 만들기'}</button></form>
 {result.length>0&&<section className="tool-panel"><h2>만든 링크</h2><button onClick={()=>copy(result.map(l=>l.label+'\n'+SITE_ORIGIN+'/l/'+l.short_code).join('\n\n'))}>전부 복사</button>{result.map(l=><div className="link-preview" key={l.id}><strong>{l.label}{l.reused?' · 기존 링크':''}{l.archived?' · 보관 중':''}</strong><code>{SITE_ORIGIN}/l/{l.short_code}</code><div className="actions"><button onClick={()=>copy(SITE_ORIGIN+'/l/'+l.short_code)}>짧은 링크 복사</button><button onClick={()=>copy(l.url)}>긴 링크 복사</button><button onClick={()=>showQr(SITE_ORIGIN+'/l/'+l.short_code)}>QR</button></div></div>)}</section>}
 <details className="tool-panel"><summary>채널 관리</summary><form onSubmit={async e=>{e.preventDefault();const f=e.currentTarget;const v=await mutate('/api/channels','POST',Object.fromEntries(new FormData(f)));if(v)f.reset();}}><div className="tool-fields">{[['name','채널 이름'],['code','단축 코드 앞부분'],['source','utm_source'],['medium','utm_medium'],['content_prefix','소재 접두사'],['note','설명']].map(([k,title])=><label key={k}>{title}<input name={k} required={['name','code','source','medium'].includes(k)}/></label>)}<label>소재 구분<select name="content_mode"><option value="none">없음</option><option value="serial">순번</option><option value="date">날짜</option><option value="free">자유 입력</option></select></label></div><button disabled={busy}>채널 추가</button></form>
 {data.channels.map(c=><div className="channel-row" key={c.id}><span>{c.name} · {c.source}/{c.medium}</span><button disabled={busy} onClick={()=>mutate('/api/channels','PATCH',{id:c.id,active:!c.active})}>{c.active?'숨기기':'다시 표시'}</button><button onClick={()=>{const name=prompt('채널 표시 이름',c.name);if(name)mutate('/api/channels','PATCH',{id:c.id,name});}}>이름 수정</button><button onClick={()=>{const note=prompt('채널 설명',c.note);if(note!==null)mutate('/api/channels','PATCH',{id:c.id,note});}}>설명 수정</button></div>)}</details>
 <section className="tool-panel"><h2>링크 장부 <small>{links.length}개</small></h2><div className="tool-fields"><label>검색<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="메모·소재·캠페인"/></label><label>채널<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">전체</option>{data.channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> 보관 포함</label></div>
 <div className="table-scroll"><table><thead><tr>{['채널 / 소재','메모 / 짧은 링크','클릭','전환(건)','전환율','만든 날','관리'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{links.map(l=><tr key={l.id}><td>{data.channels.find(c=>c.id===l.channel_id)?.name||'수동'}<br/>{l.content||'—'}</td><td>{l.label}<br/><code>{SITE_ORIGIN}/l/{l.short_code}</code></td><td>{l.clicks}</td><td>{l.conversions}</td><td>{l.clicks?(l.conversions/l.clicks*100).toFixed(1)+'%':'—'}</td><td>{new Date(l.created_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})}</td><td><div className="actions"><button onClick={()=>copy(SITE_ORIGIN+'/l/'+l.short_code)}>복사</button><button onClick={()=>showQr(SITE_ORIGIN+'/l/'+l.short_code)}>QR</button><button disabled={busy} onClick={()=>mutate('/api/utm-links','PATCH',{id:l.id,archived:!l.archived})}>{l.archived?'복원':'보관'}</button><button onClick={()=>{const label=prompt('메모 수정',l.label);if(label!==null)mutate('/api/utm-links','PATCH',{id:l.id,label});}}>메모</button></div></td></tr>)}</tbody></table></div>{!links.length&&<p>조건에 맞는 링크가 없습니다.</p>}</section>
 {qr&&<div className="qr-dialog" role="dialog" aria-modal="true" aria-label="QR 코드"><div><button autoFocus onClick={()=>setQr('')}>닫기</button><img src={qr} alt="선택한 단축 링크 QR 코드" width="320" height="320"/><a href={qr} download="aveniq-qr.png">QR 다운로드</a></div></div>}
 </>;
}
